name: "Continuous Integration"

on: 
  push:

jobs:

  tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - operating-system: 'ubuntu-latest'
            silverstripe-version: '5.0'
            php-version: '8.1'
          - operating-system: 'ubuntu-latest'
            silverstripe-version: '4.0'
            php-version: '8.0'
          - operating-system: 'ubuntu-latest'
            silverstripe-version: '4.0'
            php-version: '7.4'
  
    name: SS ${{ matrix.silverstripe-version }}, PHP ${{ matrix.php-version }}
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          command: update --with silverstripe/framework:^${{ matrix.silverstripe-version }}
          php_version: ${{ matrix.php-version }}
          php_extensions: intl
      - run: |
          ./vendor/bin/phpunit -c phpunit.xml.dist \
          --coverage-clover ./coverage.xml
