name: "Github Autorelease"

on: 
  push:
    tags:
      - "v*"

jobs:

  release:
    name: "Create Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false

  